### ISSUE TITLE
Brightness affecting color wheel

### ISSUE THREAD

**Issue by JohnTRoth** [horfee/OctoPrint-M150control#2]
I'm sure this was by design, but many of my uses involve settings of a much lower brightness. When setting brightness low though, you darken the color wheel to the point where it just looks black - and becomes quite useless. It would be nice to not change the look of the color wheel when changing brightness - or perhaps have a toggle somewhere to disable it if there is a need for it.

**Comment by horfee** [comment]
Hello,

I agree when dimming brithness, the colorwheel is becoming less usable.
I changed it in the last release. you should uninstall and reinstall the plugin.
